travis:
  secure:
    BINSTAR_TOKEN: XFuv9yvOn11DsBA+KAz8T8NAR/sirKzxRgGkUnWNbmyfa+1fwhCIcaqxw4p5Er/MXmwXOjCavC+XSXj+Ft/8UfxiEL/ARrYofo5Kr1HlweTONFb79k0oxwcfS1rbP6xZY8vtLHagQLKAj1Lh9nREWqdDEhBqL6K8rYpaRu/WjCH78Y4+JDn9ozHNb8fpPEaX8w2jn1rwc5HBx0hMF9HHcmFRJMxmy2jgos3wC0ZpbVM8vo/dj5FN5gVWO63JWjDZK6/Aynzs+iyrEso3s6jvOkZw56d1PS4qevbamMkJgH8PYnoNIjScMBBAYdi8yfsK0iwcF65ISddZcZC+6b3/JpLZgT79y2tYU2tr+kPI7ntr5gxQr6mz+KCbbTvxAQw08nyCjyqYBi+yx/2eomPya+lOoYl+JUo3du0QsteIR1VJkMVJuYPrS9aLZY9G71Bj6+L2Db84neTc6hLXag3P39fKGE4YGjB+MalYtdWN4ptxEL5+FpqECUnMAMFIA+6o1Pbs/o8B4/mWF3WpXUPdjSsRgHZ/PFhkL+qTq8coIveLPdp6cQgku2nV8T5gc2NyVi9szd+3utsSKV0oK6tJ/BZuWoYXNRuaRRH46ux5s49gRU5+DgV495yqeaq7R6aXmh5i2+RMEMbf1TTwyYME1o8ncvV11zMYKHMe1CbVcP8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
