travis:
  secure:
    BINSTAR_TOKEN: WyXOEnuXIpAm9iUQsNiqk915ejnYon3Qg4+IflNUIJYeNrBEmUugs7nvkPtWFba1wGAzHREpK/8e1PAB2hixMDHEOY+PDnQnn1nKEtj7K/lEIdFPhxCeRwBQNp1dSf+rTR2jzQOovkXXbVMzY5UPEiE2p7mBLwTMy64qLIiMZGyhQT7z6P5V3laUaV1nmoq65xANkkEXEfDk1bwCNA6a72UbHP9fM1qh+lwmoqul2V/dEy7vZIkOqCrZ6oTYJIxlQ20OPLAQm3vi9+j7Zju9+E2H9txtV8NZjl2zlBWoUq6UWy5W7FpmuX4YjqPpp1A0881FQyP5vHWMRWT+H2wtBMQREizUSZRn4F1Tc7xN2lVIHVvuTe0DZUEoCxFC7foTKm5q3m/rwmH9iad2K65x13o37k+D4VXYE/L4Y6AeLCujygW7aexv06hcCJIZPwINdwB0RLoj2q9lzuVW+V9/kKLzaZdweqOEXeqv9kANlyTrtZItitcEmJFpuOhV62w3hjjzaP+RztCmWSl6GG4XBUn2coQerc+jGz4T1bAA9PPu6GAT1givRmVG2MPXqLg5qyPFFEGM2YmSyIwFl4IuNZTMa797KRWLjWoqB+XRcxcoPnHIid2ioah5q4BdLmB58J17GwS1AhYH+lBrwP6/bPyaDCANvizXHack0eCkr6E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
